export const CURATED_WORKERS = [
	{
		fullName: "Yonas Alemu",
		fayda: "F-2345-6789-CD",
		phone: "+251911223300",
		gender: "M",
		area: "bole",
		languages: ["am", "en"],
		experienceYears: 5,
		hasHealthCard: false,
		hasPoliceClearance: true,
		roles: ["driver"],
		bio: "Experienced driver, knows Addis well.",
		tier: "verified",
		ratingAverage: 4.6,
		stationCode: "aa-bole-w03",
		agentKey: "agentBole",
	},
	{
		fullName: "Marta Tadesse",
		fayda: "F-3456-7890-EF",
		phone: "+251911334411",
		gender: "F",
		area: "bole",
		languages: ["am"],
		experienceYears: 3,
		hasHealthCard: true,
		hasPoliceClearance: false,
		roles: ["house_maid"],
		bio: "Reliable household support with recent references.",
		tier: "basic",
		ratingAverage: 4.2,
		stationCode: "aa-bole-w03",
		agentKey: "agentBole",
	},
	{
		fullName: "Dawit Mekonnen",
		fayda: "F-4567-8901-GH",
		phone: "+251911445522",
		gender: "M",
		area: "megenagna",
		languages: ["am", "om"],
		experienceYears: 7,
		hasHealthCard: false,
		hasPoliceClearance: true,
		roles: ["guard"],
		bio: "Night shift guard, ex-military.",
		tier: "verified",
		ratingAverage: 4.7,
		stationCode: "aa-yeka-w08",
		agentKey: "agentMegenagna",
	},
	{
		fullName: "Hanna Lemma",
		fayda: "F-5678-9012-IJ",
		phone: "+251911556633",
		gender: "F",
		area: "bole",
		languages: ["am", "en"],
		experienceYears: 4,
		hasHealthCard: true,
		hasPoliceClearance: false,
		roles: ["nanny"],
		bio: "Warm with children, references available.",
		tier: "basic",
		ratingAverage: 4.4,
		stationCode: "aa-bole-w03",
		agentKey: "agentBole",
	},
	{
		fullName: "Tariku Bekele",
		fayda: "F-6789-0123-KL",
		phone: "+251911667744",
		gender: "M",
		area: "megenagna",
		languages: ["am", "en"],
		experienceYears: 2,
		hasHealthCard: true,
		hasPoliceClearance: false,
		roles: ["waiter"],
		bio: "Fast learner for hospitality shifts.",
		tier: "basic",
		ratingAverage: 4.0,
		stationCode: "aa-yeka-w08",
		agentKey: "agentMegenagna",
	},
	{
		fullName: "Bethel Girma",
		fayda: "F-7890-1234-MN",
		phone: "+251911778855",
		gender: "F",
		area: "bole",
		languages: ["am", "ti"],
		experienceYears: 6,
		hasHealthCard: true,
		hasPoliceClearance: true,
		roles: ["cook"],
		bio: "Cooks Ethiopian and Italian meals.",
		tier: "trusted",
		ratingAverage: 4.9,
		stationCode: "aa-bole-w03",
		agentKey: "agentBole",
	},
	{
		fullName: "Solomon Worku",
		fayda: "F-8901-2345-OP",
		phone: "+251911889966",
		gender: "M",
		area: "kazanchis",
		languages: ["am"],
		experienceYears: 1,
		hasHealthCard: false,
		hasPoliceClearance: false,
		roles: ["cleaner"],
		bio: "Available for offices and compounds.",
		tier: "basic",
		ratingAverage: null,
		stationCode: "aa-bole-w03",
		agentKey: "agentBole",
	},
	{
		fullName: "Selam Desta",
		fayda: "F-9012-3456-QR",
		phone: "+251911990077",
		gender: "F",
		area: "megenagna",
		languages: ["am", "en"],
		experienceYears: 3,
		hasHealthCard: true,
		hasPoliceClearance: false,
		roles: ["barista"],
		bio: "Latte art, espresso machine certified.",
		tier: "trained",
		ratingAverage: 4.5,
		stationCode: "aa-yeka-w08",
		agentKey: "agentMegenagna",
	},
	{
		fullName: "Henok Fikru",
		fayda: "F-0123-4567-ST",
		phone: "+251912001188",
		gender: "M",
		area: "mexico",
		languages: ["am", "ar"],
		experienceYears: 8,
		hasHealthCard: false,
		hasPoliceClearance: true,
		roles: ["driver"],
		bio: "Long-haul and delivery experience.",
		tier: "verified",
		ratingAverage: 4.3,
		stationCode: "aa-bole-w03",
		agentKey: "agentBole",
	},
	{
		fullName: "Tigist Kebede",
		fayda: "F-1230-4560-UV",
		phone: "+251912112299",
		gender: "F",
		area: "megenagna",
		languages: ["am"],
		experienceYears: 2,
		hasHealthCard: true,
		hasPoliceClearance: false,
		roles: ["house_maid", "cleaner"],
		bio: "Flexible household and cleaning work.",
		tier: "basic",
		ratingAverage: 4.1,
		stationCode: "aa-yeka-w08",
		agentKey: "agentMegenagna",
	},
	{
		fullName: "Mekonnen Zeleke",
		fayda: "F-2340-5670-WX",
		phone: "+251912223300",
		gender: "M",
		area: "megenagna",
		languages: ["am", "ti"],
		experienceYears: 10,
		hasHealthCard: false,
		hasPoliceClearance: true,
		roles: ["guard"],
		bio: "Senior guard, day and night shifts.",
		tier: "trusted",
		ratingAverage: 4.8,
		stationCode: "aa-yeka-w08",
		agentKey: "agentMegenagna",
	},
	{
		fullName: "Rahel Assefa",
		fayda: "F-3450-6780-YZ",
		phone: "+251912334411",
		gender: "F",
		area: "summit",
		languages: ["am", "en"],
		experienceYears: 5,
		hasHealthCard: true,
		hasPoliceClearance: true,
		roles: ["cook", "nanny"],
		bio: "Experienced family cook and childcare helper.",
		tier: "trained",
		ratingAverage: 4.6,
		stationCode: "aa-bole-w03",
		agentKey: "agentBole",
	},
	{
		fullName: "Abel Seyoum",
		fayda: "F-4560-7890-AB",
		phone: "+251912445522",
		gender: "M",
		area: "megenagna",
		languages: ["am", "en", "om"],
		experienceYears: 3,
		hasHealthCard: true,
		hasPoliceClearance: false,
		roles: ["waiter", "barista"],
		bio: "Hospitality graduate.",
		tier: "trained",
		ratingAverage: 4.4,
		stationCode: "aa-yeka-w08",
		agentKey: "agentMegenagna",
	},
	{
		fullName: "Genet Tola",
		fayda: "F-5670-8900-CD",
		phone: "+251912556633",
		gender: "F",
		area: "kirkos",
		languages: ["am"],
		experienceYears: 4,
		hasHealthCard: false,
		hasPoliceClearance: false,
		roles: ["cleaner"],
		bio: "Office and post-construction cleaning.",
		tier: "basic",
		ratingAverage: 4.0,
		stationCode: "aa-bole-w03",
		agentKey: "agentBole",
	},
	{
		fullName: "Mulugeta Berhanu",
		fayda: "F-6780-9010-EF",
		phone: "+251912667744",
		gender: "M",
		area: "bole",
		languages: ["am", "en"],
		experienceYears: 2,
		hasHealthCard: true,
		hasPoliceClearance: false,
		roles: ["barista", "waiter"],
		bio: "Cafe and restaurant floor work.",
		tier: "basic",
		ratingAverage: 4.2,
		stationCode: "aa-bole-w03",
		agentKey: "agentBole",
	},
	{
		fullName: "Helen Wondimu",
		fayda: "F-8900-1230-IJ",
		phone: "+251912889966",
		gender: "F",
		area: "megenagna",
		languages: ["am", "en"],
		experienceYears: 7,
		hasHealthCard: true,
		hasPoliceClearance: true,
		roles: ["nanny"],
		bio: "Strong references for childcare.",
		tier: "trusted",
		ratingAverage: 4.9,
		stationCode: "aa-yeka-w08",
		agentKey: "agentMegenagna",
	},
	{
		fullName: "Kalkidan Tesema",
		fayda: "F-9010-2340-KT",
		phone: "+251912990077",
		gender: "F",
		area: "bole",
		languages: ["am", "en"],
		experienceYears: 9,
		hasHealthCard: true,
		hasPoliceClearance: true,
		roles: ["chef"],
		bio: "Head chef for restaurant and private-event kitchens.",
		tier: "trusted",
		ratingAverage: 4.8,
		stationCode: "aa-bole-w03",
		agentKey: "agentBole",
	},
	{
		fullName: "Natnael Teshome",
		fayda: "F-0120-3450-NT",
		phone: "+251913001188",
		gender: "M",
		area: "megenagna",
		languages: ["am", "en"],
		experienceYears: 4,
		hasHealthCard: true,
		hasPoliceClearance: false,
		roles: ["line_cook"],
		bio: "Line cook for prep, grill, and high-volume service shifts.",
		tier: "trained",
		ratingAverage: 4.3,
		stationCode: "aa-yeka-w08",
		agentKey: "agentMegenagna",
	},
	{
		fullName: "Sofia Mohammed",
		fayda: "F-1230-4560-SM",
		phone: "+251913112299",
		gender: "F",
		area: "bole",
		languages: ["am", "ar"],
		experienceYears: 2,
		hasHealthCard: true,
		hasPoliceClearance: false,
		roles: ["dishwasher"],
		bio: "Kitchen steward for dishwashing, sanitation, and prep support.",
		tier: "basic",
		ratingAverage: 4.1,
		stationCode: "aa-bole-w03",
		agentKey: "agentBole",
	},
] as const;
