const DEMO_PASSWORDS = {
	opsManager: "OpsManagerPass#1!",
	supervisor: "SupervisorPass#1!",
	agentBole: "AgentBolePass#1!",
	agentMegenagna: "AgentMegaPass#1!",
	hrFinance: "HrFinancePass#1!",
	executive: "ExecutivePass#1!",
} as const;

export const STAFF_SEEDS = [
	{
		key: "opsManager",
		email: "ops@wez.local",
		name: "Ops Manager",
		role: "ops_manager",
		password: DEMO_PASSWORDS.opsManager,
	},
	{
		key: "supervisor",
		email: "supervisor@wez.local",
		name: "Bole Station Supervisor",
		role: "station_supervisor",
		password: DEMO_PASSWORDS.supervisor,
	},
	{
		key: "agentBole",
		email: "agent.bole@wez.local",
		name: "Hanna B.",
		role: "agent",
		password: DEMO_PASSWORDS.agentBole,
	},
	{
		key: "agentMegenagna",
		email: "agent.megenagna@wez.local",
		name: "Dawit M.",
		role: "agent",
		password: DEMO_PASSWORDS.agentMegenagna,
	},
	{
		key: "hrFinance",
		email: "hr.finance@wez.local",
		name: "HR Finance Manager",
		role: "hr_manager",
		password: DEMO_PASSWORDS.hrFinance,
	},
	{
		key: "executive",
		email: "executive@wez.local",
		name: "Executive Viewer",
		role: "executive_viewer",
		password: DEMO_PASSWORDS.executive,
	},
] as const;

export const ROLE_SEEDS = [
	{
		id: "house_maid",
		name: "House Maid",
		category: "domestic",
		commType: "flat",
		commValue: 1500,
		salaryMinCents: 200_000n,
		salaryMaxCents: 600_000n,
	},
	{
		id: "nanny",
		name: "Nanny",
		category: "domestic",
		commType: "flat",
		commValue: 2000,
		salaryMinCents: 250_000n,
		salaryMaxCents: 700_000n,
	},
	{
		id: "cook",
		name: "Cook",
		category: "domestic",
		commType: "flat",
		commValue: 1800,
		salaryMinCents: 300_000n,
		salaryMaxCents: 800_000n,
	},
	{
		id: "chef",
		name: "Chef",
		category: "hospitality",
		commType: "percent",
		commValue: 12,
		salaryMinCents: 700_000n,
		salaryMaxCents: 1_800_000n,
	},
	{
		id: "line_cook",
		name: "Line Cook",
		category: "hospitality",
		commType: "percent",
		commValue: 10,
		salaryMinCents: 450_000n,
		salaryMaxCents: 1_000_000n,
	},
	{
		id: "dishwasher",
		name: "Dishwasher",
		category: "hospitality",
		commType: "flat",
		commValue: 1000,
		salaryMinCents: 200_000n,
		salaryMaxCents: 450_000n,
	},
	{
		id: "barista",
		name: "Barista",
		category: "hospitality",
		commType: "percent",
		commValue: 10,
		salaryMinCents: 350_000n,
		salaryMaxCents: 900_000n,
	},
	{
		id: "waiter",
		name: "Waiter / Waitress",
		category: "hospitality",
		commType: "percent",
		commValue: 10,
		salaryMinCents: 300_000n,
		salaryMaxCents: 800_000n,
	},
	{
		id: "cleaner",
		name: "Cleaner",
		category: "facilities",
		commType: "flat",
		commValue: 1200,
		salaryMinCents: 200_000n,
		salaryMaxCents: 500_000n,
	},
	{
		id: "guard",
		name: "Security Guard",
		category: "facilities",
		commType: "flat",
		commValue: 1500,
		salaryMinCents: 300_000n,
		salaryMaxCents: 700_000n,
	},
	{
		id: "driver",
		name: "Driver",
		category: "transport",
		commType: "percent",
		commValue: 8,
		salaryMinCents: 500_000n,
		salaryMaxCents: 1_500_000n,
	},
] as const;

export const LOOKUP_SEEDS = [
	{ kind: "languages", value: "am", labelEn: "Amharic", labelAm: "Amharic", sortOrder: 1 },
	{ kind: "languages", value: "en", labelEn: "English", labelAm: "English", sortOrder: 2 },
	{ kind: "languages", value: "om", labelEn: "Oromiffa", labelAm: "Oromiffa", sortOrder: 3 },
	{ kind: "languages", value: "ti", labelEn: "Tigrinya", labelAm: "Tigrinya", sortOrder: 4 },
	{ kind: "languages", value: "ar", labelEn: "Arabic", labelAm: "Arabic", sortOrder: 5 },
	{ kind: "woredas", value: "bole", labelEn: "Bole", labelAm: "Bole", sortOrder: 1 },
	{ kind: "woredas", value: "megenagna", labelEn: "Megenagna", labelAm: "Megenagna", sortOrder: 2 },
	{ kind: "woredas", value: "kazanchis", labelEn: "Kazanchis", labelAm: "Kazanchis", sortOrder: 3 },
	{ kind: "woredas", value: "mexico", labelEn: "Mexico", labelAm: "Mexico", sortOrder: 4 },
	{ kind: "woredas", value: "summit", labelEn: "Summit", labelAm: "Summit", sortOrder: 5 },
	{ kind: "religions", value: "orthodox", labelEn: "Orthodox", labelAm: "Orthodox", sortOrder: 1 },
	{ kind: "religions", value: "muslim", labelEn: "Muslim", labelAm: "Muslim", sortOrder: 2 },
	{ kind: "religions", value: "protestant", labelEn: "Protestant", labelAm: "Protestant", sortOrder: 3 },
	{ kind: "religions", value: "catholic", labelEn: "Catholic", labelAm: "Catholic", sortOrder: 4 },
	{
		kind: "religions",
		value: "prefer_not_to_say",
		labelEn: "Prefer not to say",
		labelAm: "Prefer not to say",
		sortOrder: 99,
	},
] as const;

export const EMPLOYER_SEEDS = [
	{
		key: "sunriseCafe",
		type: "business",
		name: "Bole Sunrise Cafe",
		contactName: "Mekdes Alemu",
		phone: "+251911101001",
		email: "owner@bolesunrise.local",
		area: "bole",
		tin: "TIN-100001",
		businessLicense: "BL-BOLE-1001",
		businessCategory: "cafe",
	},
	{
		key: "familyRestaurant",
		type: "business",
		name: "Megenagna Family Restaurant",
		contactName: "Samuel Bekele",
		phone: "+251911101002",
		email: "samuel@megenagnarest.local",
		area: "megenagna",
		tin: "TIN-100002",
		businessLicense: "BL-MEG-1002",
		businessCategory: "restaurant",
	},
	{
		key: "asterHousehold",
		type: "household",
		name: "Aster Household",
		contactName: "Aster Tesfaye",
		phone: "+251911101003",
		area: "kazanchis",
		fayda: "F-7001-1001-AA",
	},
	{
		key: "dawitHousehold",
		type: "household",
		name: "Dawit Household",
		contactName: "Dawit Kebede",
		phone: "+251911101004",
		area: "yeka",
		fayda: "F-7001-1002-BB",
	},
] as const;

export const NOTIFICATION_TEMPLATE_SEEDS = [
	{
		key: "auth.otp",
		channel: "sms",
		bodyEn: "Your Wez code: {{code}}. Valid 5 minutes.",
		bodyAm: "Your Wez code: {{code}}. Valid 5 minutes.",
	},
	{
		key: "hire_request.created.worker",
		channel: "sms",
		bodyEn:
			"{{employerName}} requested to hire you for {{roleName}} at {{salaryBirr}} ETB. Visit your station to confirm.",
		bodyAm:
			"{{employerName}} requested to hire you for {{roleName}} at {{salaryBirr}} ETB. Visit your station to confirm.",
	},
	{
		key: "hire_request.created.employer",
		channel: "email",
		subjectEn: "Wez hire request received",
		subjectAm: "Wez hire request received",
		bodyEn: "Your hire request for {{workerName}} as {{roleName}} at {{salaryBirr}} ETB was received.",
		bodyAm: "Your hire request for {{workerName}} as {{roleName}} at {{salaryBirr}} ETB was received.",
	},
	{
		key: "placement.finalized.worker",
		channel: "sms",
		bodyEn: "Placement confirmed at {{employerName}}. Salary {{salaryBirr}} ETB. Welcome.",
		bodyAm: "Placement confirmed at {{employerName}}. Salary {{salaryBirr}} ETB. Welcome.",
	},
	{
		key: "complaint.assigned",
		channel: "in_app",
		bodyEn: "Complaint {{complaintId}} was assigned to you. Severity: {{severity}}.",
		bodyAm: "Complaint {{complaintId}} was assigned to you. Severity: {{severity}}.",
	},
	{
		key: "ticket.assigned",
		channel: "in_app",
		bodyEn: "Ticket {{ticketId}} was assigned to you. Priority: {{priority}}.",
		bodyAm: "Ticket {{ticketId}} was assigned to you. Priority: {{priority}}.",
	},
] as const;
