export const AUDIT_ACTIONS = {
	authLogin: "auth.login",
	authLogout: "auth.logout",
	authFailedLogin: "auth.failed_login",
	jobCreated: "job.created",
	jobUpdated: "job.updated",
	jobClosed: "job.closed",
	workerCreated: "worker.created",
	workerProfileUpdated: "worker.profile_updated",
	employerSignedUp: "employer.signed_up",
	employerCreated: "employer.created",
	employerUpdated: "employer.updated",
	hireRequestCreated: "hire_request.created",
	hireRequestCancelled: "hire_request.cancelled",
	referralCreated: "referral.created",
	referralAccepted: "referral.accepted",
	referralDeclined: "referral.declined",
	referralDeferred: "referral.deferred",
	roleCatalogCreated: "role_catalog.created",
	roleCatalogUpdated: "role_catalog.updated",
	lookupCreated: "lookup.created",
	lookupUpdated: "lookup.updated",
	hiringPolicyUpdated: "hiring_policy.updated",
	staffUserCreated: "staff_user.created",
	staffUserUpdated: "staff_user.updated",
	staffRoleAssigned: "staff_role.assigned",
	staffRoleRevoked: "staff_role.revoked",
	locationCreated: "location.created",
	locationUpdated: "location.updated",
	locationDeactivated: "location.deactivated",
	stationCreated: "station.created",
	stationUpdated: "station.updated",
	stationAgentAssigned: "station.agent_assigned",
	stationAgentUnassigned: "station.agent_unassigned",
	placementFinalized: "placement.finalized",
	placementEnded: "placement.ended",
	complaintCreated: "complaint.created",
	complaintMediating: "complaint.mediating",
	complaintClosed: "complaint.closed",
	complaintReferredExternal: "complaint.referred_external",
	ticketCreated: "ticket.created",
	ticketAssigned: "ticket.assigned",
	ticketResolved: "ticket.resolved",
	ticketClosed: "ticket.closed",
	permissionDenied: "permission.denied",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_TARGET_TYPES = {
	job: "job",
	worker: "worker",
	employer: "employer",
	hireRequest: "hire_request",
	referral: "referral",
	roleCatalog: "role_catalog",
	lookup: "lookup",
	hiringPolicy: "hiring_policy",
	placement: "placement",
	staffUser: "staff_user",
	staffRoleAssignment: "staff_role_assignment",
	location: "location",
	station: "station",
	agentAssignment: "agent_assignment",
	auth: "auth",
	complaint: "complaint",
	ticket: "ticket",
	permission: "permission",
} as const;

export type AuditTargetType = (typeof AUDIT_TARGET_TYPES)[keyof typeof AUDIT_TARGET_TYPES];
