import { existsSync } from "node:fs";
import { Injectable } from "@nestjs/common";
import type { Complaint } from "../../domain/entities/complaint.entity";

import PDFDocument = require("pdfkit");

const PDF_MARGIN = 48;
const FONT_SIZE_TITLE = 18;
const FONT_SIZE_SECTION = 12;
const FONT_SIZE_BODY = 10;
const AMHARIC_FONT_NAME = "amharic";
const AMHARIC_TITLE =
	"\u12e8\u12cd\u132d\u0020\u1245\u122c\u1273\u0020\u122a\u1348\u122b\u120d\u0020\u12f0\u1265\u12f3\u1264";
const AMHARIC_REFERRAL_SUMMARY = [
	"\u12cc\u12dd\u0020\u12ed\u1205\u1295\u0020\u1245\u122c\u1273\u0020\u12a8\u134d\u1270\u129b\u0020\u12ad\u1265\u12f0\u1275",
	"\u0020\u1235\u120b\u1208\u12cd\u0020\u12c8\u12ed\u121d\u0020\u1260\u1270\u1308\u1262\u1290\u1275\u0020\u1261\u12f5\u1295",
	"\u0020\u1235\u1208\u1270\u1218\u122b\u0020\u1208\u12cd\u132d\u0020\u12a0\u12ab\u120d\u0020\u12eb\u1235\u1270\u120b\u120d\u134b\u120d\u1362",
	"\u0020\u1270\u1240\u1263\u12e9\u0020\u12a0\u12ab\u120d\u0020\u12e8\u1245\u122c\u1273\u12cd\u1295\u0020\u1218\u1228\u1303",
	"\u0020\u12a5\u1295\u12f2\u1218\u1228\u121d\u122d\u1363\u0020\u12a0\u1235\u1348\u120b\u130a\u0020\u12a8\u1206\u1290",
	"\u0020\u1270\u12eb\u12eb\u12e5\u0020\u12c8\u1308\u1296\u127d\u1295\u0020\u12a5\u1295\u12f2\u12eb\u1290\u130b\u130d\u122d\u1363",
	"\u0020\u12a5\u1293\u0020\u1208\u12cc\u12dd\u0020\u12e8\u1270\u1308\u1262\u1290\u1275\u0020\u1218\u12dd\u1308\u1265",
	"\u0020\u12e8\u12cd\u132d\u0020\u1309\u12f3\u12ed\u0020\u1218\u1208\u12eb\u0020\u12a5\u1295\u12f2\u1230\u1325\u0020\u12ed\u1320\u12e8\u1243\u120d\u1362",
].join("");
const AMHARIC_FONT_CANDIDATES = [
	process.env.AGREEMENT_AMHARIC_FONT_PATH,
	"C:\\Windows\\Fonts\\nyala.ttf",
	"/usr/share/fonts/truetype/noto/NotoSansEthiopic-Regular.ttf",
	"/usr/share/fonts/truetype/abyssinica/AbyssinicaSIL-Regular.ttf",
] as const;

export type ComplaintReferralLetterPayload = {
	complaint: Complaint;
	generatedBy: string;
};

const display = (value: string | null | undefined): string => {
	if (!value?.trim()) return "-";
	return value;
};

const addKeyValue = (doc: PDFKit.PDFDocument, label: string, value: string) => {
	doc.font("Helvetica-Bold").text(label, { continued: true });
	doc.font("Helvetica").text(` ${value}`);
};

const getAmharicFontPath = (): string | null => {
	for (const candidate of AMHARIC_FONT_CANDIDATES) {
		if (candidate && existsSync(candidate)) return candidate;
	}
	return null;
};

const addAmharicText = (doc: PDFKit.PDFDocument, value: string, hasAmharicFont: boolean) => {
	if (hasAmharicFont) {
		doc.font(AMHARIC_FONT_NAME).text(value);
		return;
	}
	doc.font("Helvetica-Oblique").text("Amharic copy requires AGREEMENT_AMHARIC_FONT_PATH to point at an Ethiopic font.");
};

@Injectable()
export class ComplaintReferralLetterService {
	async generate(payload: ComplaintReferralLetterPayload): Promise<Buffer> {
		const { complaint } = payload;
		const doc = new PDFDocument({ margin: PDF_MARGIN, size: "A4", info: { Title: "Wez Complaint Referral Letter" } });
		const amharicFontPath = getAmharicFontPath();
		const hasAmharicFont = Boolean(amharicFontPath);
		const chunks: Buffer[] = [];

		if (amharicFontPath) {
			doc.registerFont(AMHARIC_FONT_NAME, amharicFontPath);
		}
		doc.on("data", (chunk: Buffer) => chunks.push(chunk));
		const done = new Promise<Buffer>((resolve) => {
			doc.on("end", () => resolve(Buffer.concat(chunks)));
		});

		doc.font("Helvetica-Bold").fontSize(FONT_SIZE_TITLE).text("Wez External Complaint Referral Letter", {
			align: "center",
		});
		if (hasAmharicFont) {
			doc.font(AMHARIC_FONT_NAME).fontSize(FONT_SIZE_SECTION).text(AMHARIC_TITLE, { align: "center" });
		}
		doc.moveDown();

		doc
			.font("Helvetica")
			.fontSize(FONT_SIZE_BODY)
			.text(`Generated: ${new Date().toISOString().slice(0, 10)}`);
		doc.text("To: Ministry of Labor and Skills / police / health authority");
		doc.moveDown();

		doc.font("Helvetica-Bold").fontSize(FONT_SIZE_SECTION).text("Complaint summary");
		doc.fontSize(FONT_SIZE_BODY);
		addKeyValue(doc, "Complaint ID:", complaint.id);
		addKeyValue(doc, "External case ID:", display(complaint.externalCaseId));
		addKeyValue(doc, "Status:", complaint.status);
		addKeyValue(doc, "Severity:", complaint.severity);
		addKeyValue(doc, "Category:", complaint.type);
		addKeyValue(doc, "Filed by:", `${complaint.filedByType} ${display(complaint.filedByName ?? complaint.filedById)}`);
		addKeyValue(doc, "Against:", `${complaint.againstType} ${display(complaint.againstName ?? complaint.againstId)}`);
		addKeyValue(doc, "Taking station:", display(complaint.stationName));
		addKeyValue(doc, "Placement ID:", display(complaint.placementId));
		addKeyValue(doc, "Generated by:", payload.generatedBy);

		doc.moveDown();
		doc.font("Helvetica-Bold").fontSize(FONT_SIZE_SECTION).text("Referral note");
		doc
			.font("Helvetica")
			.fontSize(FONT_SIZE_BODY)
			.text(
				"Wez is referring this complaint for external review because it was marked as high severity or escalated by compliance staff. The receiving authority should review the complaint facts, contact the parties as needed, and provide an external case reference for Wez compliance records.",
			);

		doc.moveDown();
		doc.font("Helvetica-Bold").text("Complaint description");
		doc.font("Helvetica").text(complaint.description);

		doc.moveDown();
		doc.font("Helvetica-Bold").fontSize(FONT_SIZE_SECTION).text("Amharic summary");
		addAmharicText(doc, AMHARIC_REFERRAL_SUMMARY, hasAmharicFont);

		doc.moveDown(2);
		doc.font("Helvetica-Bold").text("Compliance signature");
		doc.moveDown();
		doc.font("Helvetica").text("Name: __________________________________________");
		doc.moveDown();
		doc.text("Signature: _______________________________________");
		doc.moveDown();
		doc.text("Date: ____________________________________________");

		doc.end();
		return done;
	}
}
